backend:
  name: github
  repo: "sarvhindustries/sarvh.in" # <-- owner/repo
  branch: "main"
  open_authoring: false
  client_id: "GITHUB_OAUTH_CLIENT_ID" # <-- replace with your GitHub OAuth App Client ID

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

publish_mode: editorial_workflow # create PRs for changes (safer)

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home page (raw HTML)"
        name: "home"
        fields:
          - { label: "Raw HTML", name: "body", widget: "code", modes: ["html"] }
